# Generated by Django 3.2.6 on 2021-09-17 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.common.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_officebudget_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=apps.common.models.FlexibleForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=apps.common.models.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.product'),
        ),
        migrations.AlterField(
            model_name='orderprogressstatus',
            name='office_vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.officevendor'),
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
