# Generated by Django 3.2.6 on 2021-11-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211112_1904'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together={('office', 'vendor', 'keyword')},
        ),
    ]
