# Generated by Django 3.2.6 on 2021-09-11 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.common.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', apps.common.models.BlankTextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('image', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor', apps.common.models.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vendor')),
            ],
            options={
                'ordering': ('-updated_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=1)),
                ('office', apps.common.models.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.office')),
                ('product', apps.common.models.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.cartproduct')),
                ('user', apps.common.models.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
                'abstract': False,
            },
        ),
    ]
