# Generated by Django 3.2.6 on 2021-11-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officeproduct',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='officeproduct',
            unique_together={('office', 'product')},
        ),
    ]
