# Generated by Django 3.2.6 on 2021-09-13 10:16

import django.db.models.deletion
from django.db import migrations, models

import apps.common.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0002_cart_cartproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProgressStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Complete'), (1, 'In Progress')], default=0)),
                ('office_vendor', apps.common.models.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.officevendor')),
            ],
            options={
                'ordering': ('-updated_at',),
                'abstract': False,
            },
        ),
    ]
