# Generated by Django 3.2.6 on 2021-11-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211117_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='instant_checkout',
            field=models.BooleanField(default=True),
        ),
    ]
