# Generated by Django 3.2.6 on 2021-11-12 19:36

import django.db.models.deletion
from django.db import migrations, models

import apps.common.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211112_1904'),
        ('orders', '0002_alter_keyword_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='keyword',
            new_name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='orders.Keyword'),
        ),
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='office',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='task_status',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='vendor',
        ),
        migrations.CreateModel(
            name='OfficeKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=16)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.keyword')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='accounts.office')),
                ('vendor', apps.common.models.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='accounts.vendor')),
            ],
            options={
                'unique_together': {('office', 'vendor', 'keyword')},
            },
        ),
    ]
