# Generated by Django 3.2.6 on 2021-11-01 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_vendororder_invoice_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-order_date',)},
        ),
    ]
