# Generated by Django 3.2.6 on 2021-11-12 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_keyword_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='name',
            new_name='keyword',
        ),
    ]
