# Generated by Django 3.2.6 on 2021-11-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20211125_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororderproduct',
            name='tracking_link',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='vendororderproduct',
            name='vendor_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendororderproduct',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('shipped', 'Shipped'), ('arrived', 'Arrived'), ('received', 'Received')], default='open', max_length=100),
        ),
    ]
