# Generated by Django 3.2.6 on 2021-11-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_name_keyword_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officekeyword',
            name='task_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FETCH_COMPLETE', 'Fetching Completed'), ('COMPLETE', 'Completed'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=16),
        ),
    ]
