# Generated by Django 3.2.6 on 2021-11-02 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_office_options'),
        ('orders', '0005_inventoryproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriteproduct',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_products', to='accounts.office'),
        ),
        migrations.AlterField(
            model_name='inventoryproduct',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_products', to='accounts.office'),
        ),
    ]
