# Generated by Django 3.2.6 on 2021-11-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20211102_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_unit',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
