# Generated by Django 3.2.6 on 2021-12-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20211126_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('processing', 'Processing'), ('waitingapproval', 'Waiting Approval')], default='processing', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendororder',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('processing', 'Processing'), ('waitingapproval', 'Waiting Approval')], default='processing', max_length=100),
        ),
    ]
