# Generated by Django 3.2.6 on 2021-11-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_office_options'),
        ('orders', '0007_product_product_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryproduct',
            options={},
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='product_unit',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryproduct',
            unique_together={('office', 'product_id')},
        ),
    ]
