# Generated by Django 3.2.6 on 2021-12-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20211209_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororderproduct',
            name='tracking_number',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
