# Generated by Django 3.2.6 on 2021-09-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210929_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='retail_price',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='vendor_categories',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
