# Generated by Django 3.2.6 on 2021-10-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210930_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororderproduct',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
