# Generated by Django 3.2.6 on 2021-12-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_vendororderproduct_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororder',
            name='vendor_order_reference',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
