# Generated by Django 3.2.6 on 2021-10-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_vendororderproduct_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='save_for_later',
            field=models.BooleanField(default=False),
        ),
    ]
