# Generated by Django 3.2.6 on 2022-01-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20220118_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('processing', 'Processing'), ('waitingapproval', 'Waiting Approval'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('backordered', 'Back Ordered'), ('returned', 'Returned')], default='processing', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendororder',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('processing', 'Processing'), ('waitingapproval', 'Waiting Approval'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('backordered', 'Back Ordered'), ('returned', 'Returned')], default='processing', max_length=100),
        ),
    ]
