# Generated by Django 3.2.6 on 2021-10-06 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0010_cart_save_for_later'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderprogressstatus',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderprogressstatus',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('processing', 'In Progress')], default='complete', max_length=16),
        ),
    ]
