# Generated by Django 3.2.6 on 2021-10-07 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20210923_0950'),
        ('orders', '0011_auto_20211006_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
        migrations.RenameField(
            model_name='orderprogressstatus',
            old_name='status',
            new_name='checkout_status',
        ),
        migrations.AddField(
            model_name='orderprogressstatus',
            name='order_status',
            field=models.CharField(choices=[('complete', 'Complete'), ('processing', 'In Progress')], default='complete', max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'office', 'product')},
        ),
    ]
