# Generated by Django 3.2.6 on 2022-01-27 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.common.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0011_auto_20220120_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='vendororder',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendororderproduct',
            name='rejected_reason',
            field=models.CharField(blank=True, choices=[('noneed', 'Not Needed'), ('wrong', 'Wrong Item'), ('expensive', 'Expensive'), ('other', 'Other')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('processing', 'Processing'), ('waitingapproval', 'Waiting Approval'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('backordered', 'Back Ordered'), ('returned', 'Returned'), ('rejected', 'Rejected')], default='processing', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendororder',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('processing', 'Processing'), ('waitingapproval', 'Waiting Approval'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('backordered', 'Back Ordered'), ('returned', 'Returned'), ('rejected', 'Rejected')], default='processing', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendororderproduct',
            name='vendor_order',
            field=apps.common.models.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='orders.vendororder'),
        ),
    ]
