# Generated by Django 3.2.6 on 2022-02-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_vendororderproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('processing', 'Processing'), ('waitingapproval', 'Pending Approval'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('backordered', 'Back Ordered'), ('returned', 'Returned'), ('rejected', 'Rejected')], default='processing', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendororder',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('processing', 'Processing'), ('waitingapproval', 'Pending Approval'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('backordered', 'Back Ordered'), ('returned', 'Returned'), ('rejected', 'Rejected')], default='processing', max_length=100),
        ),
    ]
