# Generated by Django 3.2.6 on 2022-02-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_vendororderproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendororderproduct',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Processing'), ('shipped', 'Shipped'), ('arrived', 'Arrived'), ('received', 'Received'), ('rejected', 'Rejected'), ('waitingapproval', 'Pending Approval')], max_length=100, null=True),
        ),
    ]
