# Generated by Django 3.2.6 on 2022-02-15 23:00

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220113_1634'),
        ('orders', '0017_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'])),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.office')),
            ],
            options={
                'ordering': ('-updated_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='officeproduct',
            name='office_product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.officeproductcategory'),
        ),
    ]
