# Generated by Django 3.2.6 on 2022-02-21 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220113_1634'),
        ('orders', '0018_auto_20220215_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officeproductcategory',
            options={},
        ),
        migrations.AlterField(
            model_name='officeproduct',
            name='office_product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='orders.officeproductcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='officeproductcategory',
            unique_together={('office', 'name')},
        ),
    ]
