# Generated by Django 3.2.6 on 2022-03-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_officeproductcategory_predefined'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororder',
            name='nickname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
