# Generated by Django 3.2.6 on 2022-03-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_vendororder_nickname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('created_at',)},
        ),
    ]
