# Generated by Django 3.2.6 on 2022-03-20 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20220320_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_products', to='orders.product'),
        ),
    ]
