# Generated by Django 3.2.6 on 2022-03-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20220323_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeproduct',
            name='product_vendor_status',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
