# Generated by Django 3.2.6 on 2022-04-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20220405_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
