# Generated by Django 3.2.6 on 2022-04-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_product_manufacturer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororderproduct',
            name='budget_spend_type',
            field=models.CharField(blank=True, choices=[('dental', 'Dental Supply Budget'), ('office', 'Front Office Supply Budget'), ('miscellaneous', 'Other')], db_index=True, default='dental', max_length=64, null=True),
        ),
    ]
