# Generated by Django 3.2.6 on 2022-04-20 16:45

from django.db import migrations, models


def migrate_order_status(apps, schema_editor):
    Order = apps.get_model("orders", "Order")

    for order in Order.objects.all():
        old_status = order.old_status
        if old_status in ("processing", "delivered", "shipped", "backordered", "returned", "pending"):
            status = "open"
        elif old_status in ("complete", "rejected", "cancelled", "received"):
            status = "closed"
        elif old_status in ("waitingapproval",):
            status = "pendingapproval"
        else:
            status = old_status

        order.status = status
        order.save()


def migrate_vendor_order_status(apps, schema_editor):
    VendorOrder = apps.get_model("orders", "VendorOrder")
    for vendor_order in VendorOrder.objects.all():
        old_status = vendor_order.old_status
        if old_status in ("processing", "delivered", "shipped", "backordered", "returned", "pending"):
            status = "open"
        elif old_status in ("complete", "rejected", "cancelled", "received"):
            status = "closed"
        elif old_status in ("waitingapproval",):
            status = "pendingapproval"
        else:
            status = old_status

        vendor_order.status = status
        vendor_order.save()


def migrate_product_status(apps, schema_editor):
    VendorOrderProduct = apps.get_model("orders", "VendorOrderProduct")
    for product in VendorOrderProduct.objects.all():
        old_status = product.old_status
        if old_status in ("open", "shipped", "arrived"):
            status = "processing"
        elif old_status in ("waitingapproval",):
            status = "pendingapproval"
        else:
            # received, rejected
            status = old_status

        product.status = status
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_vendororderproduct_budget_spend_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='old_status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pendingapproval', 'Pending Approval')], default='open', max_length=100),
        ),
        migrations.RunPython(migrate_order_status),
        migrations.RemoveField(
            model_name='order',
            name='old_status',
        ),

        migrations.RenameField(
            model_name='vendororder',
            old_name='status',
            new_name='old_status',
        ),
        migrations.AddField(
            model_name='vendororder',
            name='status',
            field=models.CharField(
                choices=[('open', 'Open'), ('closed', 'Closed'), ('pendingapproval', 'Pending Approval')], default='open', max_length=100),
        ),
        migrations.RunPython(migrate_vendor_order_status),
        migrations.RemoveField(
            model_name='vendororder',
            name='old_status',
        ),

        migrations.RenameField(
            model_name='vendororderproduct',
            old_name='status',
            new_name='old_status',
        ),
        migrations.AddField(
            model_name='vendororderproduct',
            name='status',
            field=models.CharField(blank=True, choices=[('pendingapproval', 'Pending Approval'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('backordered', 'Back Ordered'), ('returned', 'Returned'), ('cancelled', 'Cancelled'), ('received', 'Received'), ('credited', 'Credited'), ('maintenance', 'Repair/Maintenance')], max_length=100, null=True),
        ),
        migrations.RunPython(migrate_product_status),
        migrations.RemoveField(
            model_name='vendororderproduct',
            name='old_status',
        ),
    ]
