# Generated by Django 3.2.6 on 2022-05-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_auto_20220420_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer_number_origin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
