# Generated by Django 3.2.6 on 2022-06-07 09:31

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_product_manufacturer_number_origin'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='product_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
