# Generated by Django 3.2.6 on 2021-11-21 21:47

from django.db import migrations, models
import django.db.models.deletion
from apps.common.choices import BUDGET_SPEND_TYPE
import apps.common.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_order_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='promo',
            field=apps.common.models.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.promotion', null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='budget_spend_type',
            field=models.CharField(
                max_length=64,
                choices=BUDGET_SPEND_TYPE.choices,
                default=BUDGET_SPEND_TYPE.DENTAL_SUPPLY_SPEND_BUDGET,
                null=True,
                blank=True,
                db_index=True,
            )
        ),
    ]
