# Generated by Django 3.2.13 on 2022-12-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_cart_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeproduct',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='offices'),
        ),
        migrations.AddField(
            model_name='officeproduct',
            name='nickname',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='vendororderproduct',
            name='status',
            field=models.CharField(blank=True, choices=[('pendingapproval', 'Pending Approval'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('backordered', 'Back Ordered'), ('returned', 'Returned'), ('cancelled', 'Cancelled'), ('received', 'Received'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('credited', 'Credited'), ('maintenance', 'Repair/Maintenance')], max_length=100, null=True),
        ),
    ]
