# Generated by Django 3.2.6 on 2022-12-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_auto_20221214_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codenum', models.IntegerField()),
                ('proccode', models.CharField(max_length=16)),
                ('descript', models.CharField(blank=True, max_length=256, null=True)),
                ('abbrdesc', models.CharField(blank=True, max_length=50, null=True)),
                ('proccat', models.IntegerField()),
            ],
        ),
    ]
