# Generated by Django 3.2.6 on 2022-12-16 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_office_dental_api'),
        ('orders', '0043_procedurecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('count', models.IntegerField(default=0)),
                ('avgfee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('totfee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type', models.CharField(blank=True, choices=[('week', 'Procedure Week'), ('month', 'Procedure Month')], max_length=100, null=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.office')),
                ('procedurecode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.procedurecode')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
