# Generated by Django 3.2.6 on 2022-12-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_office_dental_api'),
        ('orders', '0044_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='procedure',
            unique_together={('office', 'procedurecode', 'start_date', 'type')},
        ),
    ]
