# Generated by Django 3.2.13 on 2023-01-12 21:22
from django.db import migrations


NN_VECTOR_EXPRESSION_SQL = """
ALTER TABLE orders_officeproduct 
    ADD COLUMN nn_vector tsvector 
    GENERATED ALWAYS AS (to_tsvector('english', coalesce(nickname, ''))) STORED;

CREATE EXTENSION IF NOT EXISTS btree_gin;
    
create index orders_offi_office__98ac85_gin
    on public.orders_officeproduct using gin (office_id, nn_vector);

"""


NN_VECTOR_EXPRESSION_SQL_REV = """
DROP INDEX IF EXISTS orders_offi_office__98ac85_gin;
ALTER TABLE orders_officeproduct DROP COLUMN  nn_vector;
"""



class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0048_fix_search_vectors'),
    ]

    operations = [
        migrations.RunSQL(
            NN_VECTOR_EXPRESSION_SQL, migrations.RunSQL.noop
        ),
    ]
