# Generated by Django 3.2.13 on 2023-01-12 21:22

import django.contrib.postgres.search
from django.db import migrations
import django.contrib.postgres.indexes
from django.contrib.postgres.operations import BtreeGinExtension


NN_VECTOR_EXPRESSION_SQL = """
ALTER TABLE orders_officeproduct DROP COLUMN  nn_vector;
ALTER TABLE orders_officeproduct 
    ADD COLUMN nn_vector tsvector 
    GENERATED ALWAYS AS (to_tsvector('english', coalesce(nickname, ''))) STORED;
"""


NN_VECTOR_EXPRESSION_SQL_REV = """
ALTER TABLE orders_officeproduct DROP COLUMN  nn_vector;
ALTER TABLE orders_officeproduct 
    ADD COLUMN nn_vector tsvector;
"""



class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0048_fix_search_vectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeproduct',
            name='nn_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, help_text='Nickname search vector', null=True),
        ),
        migrations.RunSQL(
            NN_VECTOR_EXPRESSION_SQL, migrations.RunSQL.noop
        ),
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name='officeproduct',
            index=django.contrib.postgres.indexes.GinIndex(fields=['office', 'nn_vector'],
                                                           name='orders_offi_office__98ac85_gin'),
        ),
    ]
