# Generated by Django 3.2.6 on 2023-01-16 14:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_officeproduct_nn_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureCategoryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proccat', models.IntegerField()),
                ('linked_slugs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
            ],
        ),
    ]
