# Generated by Django 3.2.6 on 2023-01-17 14:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_officeproduct_nn_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureCategoryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_category', models.CharField(default='Empty', max_length=256)),
                ('linked_slugs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='procedurecode',
            name='abbrdesc',
        ),
        migrations.RemoveField(
            model_name='procedurecode',
            name='codenum',
        ),
        migrations.RemoveField(
            model_name='procedurecode',
            name='itemname',
        ),
        migrations.RemoveField(
            model_name='procedurecode',
            name='proccat',
        ),
        migrations.AddField(
            model_name='procedurecode',
            name='category',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='procedurecode',
            name='summary_category',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
