# Generated by Django 3.2.6 on 2023-01-19 23:47


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0050_alter_cart_unit_price'),
        ('orders', '0051_add_linked_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedurecategorylink',
            name='category_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='procedurecategorylink',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
