# Generated by Django 3.2.6 on 2023-01-20 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0052_alter_cart_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedurecode',
            name='summary_cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.procedurecategorylink'),
        ),
    ]
