# Generated by Django 3.2.6 on 2023-01-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0053_procedurecode_summary_cate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedurecategorylink',
            old_name='summary_category',
            new_name='summary_slug',
        ),
        migrations.RemoveField(
            model_name='procedurecode',
            name='summary_category',
        ),
    ]
