# Generated by Django 4.1.5 on 2023-02-02 18:07
import datetime
from typing import NamedTuple

from django.db import migrations, models


# Copied from updater.py
class AgeParams(NamedTuple):
    inventory: datetime.timedelta
    regular: datetime.timedelta


DEFAULT_AGE_PARAMS = AgeParams(inventory=datetime.timedelta(days=7), regular=datetime.timedelta(days=14))

VENDOR_AGE = {"net_32": AgeParams(inventory=datetime.timedelta(days=1), regular=datetime.timedelta(days=2))}


ADD_FIELDS = """
ALTER TABLE orders_product ADD COLUMN inventory_refs integer DEFAULT 0;
"""

REMOVE_FIELDS = """
ALTER TABLE orders_product DROP COLUMN inventory_refs;
"""


FILL_SQL = """
WITH inventory_stats AS (
    SELECT product_id, COUNT(*) as count
    FROM orders_officeproduct
    WHERE is_inventory
    GROUP BY product_id
)
UPDATE orders_product op
SET inventory_refs = istats.count
FROM inventory_stats istats
WHERE istats.product_id = op.id
"""


FILL_PRICE_EXPIRATION_SQL = """
WITH updated_prices AS (
    SELECT
        op.id,
        CASE
            WHEN op.vendor_id = 2 THEN
                CASE
                    WHEN op.inventory_refs = 0 THEN op.updated_at + '2 days'::interval
                    ELSE op.updated_at + '1 day'::interval
                END
            ELSE
                CASE
                    WHEN op.inventory_refs = 0 THEN op.updated_at + '14 days'::interval
                    ELSE op.updated_at + '7 days'::interval
                END
        END price_expiration_value
    FROM orders_product op
)
UPDATE orders_product op
SET price_expiration = up.price_expiration_value
FROM updated_prices up
WHERE op.id = up.id;
"""

FILL_PRICE_EXPIRATION_REVERSE_SQL = """
UPDATE orders_product SET price_expiration = NULL;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0054_fix_triggers"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price_expiration",
            field=models.DateTimeField(blank=True, help_text="Price expiration", null=True),
        ),
        migrations.RunSQL(ADD_FIELDS, REMOVE_FIELDS),
        migrations.RunSQL(FILL_SQL, migrations.RunSQL.noop),
        migrations.RunSQL(FILL_PRICE_EXPIRATION_SQL, FILL_PRICE_EXPIRATION_REVERSE_SQL),
    ]
