# Generated by Django 3.2.6 on 2023-01-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0054_auto_20230120_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedurecode',
            old_name='summary_cate',
            new_name='summary_category',
        ),
    ]
