# Generated by Django 4.1.6 on 2023-02-11 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0056_product_inventory_refs2"),
    ]

    operations = [
        migrations.AddField(
            model_name="officeproduct",
            name="price_expiration",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="officeproduct",
            name="vendor",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="accounts.vendor"
            ),
        ),
    ]
