# Generated by Django 4.1.6 on 2023-03-02 21:36

import django.contrib.postgres.search
from django.db import migrations, models

ADD_SEARCH_VECTOR_SQL = """
ALTER TABLE orders_procedurecode ADD COLUMN search_vector tsvector GENERATED ALWAYS AS (
                setweight(to_tsvector('english', coalesce(proccode, '')), 'A') ||
                setweight(to_tsvector('english', coalesce(abbr_desc,'')), 'B')
                ) STORED;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0058_fill_vendor_expiration_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedurecode',
            name='abbr_desc',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.RunSQL(ADD_SEARCH_VECTOR_SQL)
    ]
