# Generated by Django 4.1.6 on 2023-03-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0061_procedure_merge_bone"),
    ]

    operations = [
        migrations.AddField(
            model_name="officeproduct",
            name="previous_office_product_category",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
