# Generated by Django 4.1.5 on 2023-03-28 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_vendor_shipping_options'),
        ('orders', '0062_officeproduct_previous_office_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeVendorShippingOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_shipping_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ov_default_shipping_option', to='orders.shippingmethod')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_options', to='accounts.office')),
                ('shipping_options', models.ManyToManyField(related_name='ov_shipping_options', to='orders.shippingmethod')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_options', to='accounts.vendor')),
            ],
            options={
                'ordering': ('-updated_at',),
                'abstract': False,
            },
        ),
    ]
