# Generated by Django 4.1.6 on 2023-03-29 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0063_shippingmethod_officevendorshippingoptions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingmethod",
            name="address",
        ),
        migrations.AlterField(
            model_name="officevendorshippingoptions",
            name="default_shipping_option",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ov_default_shipping_option",
                to="orders.shippingmethod",
            ),
        ),
    ]
