# Generated by Django 4.1.5 on 2023-03-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0064_remove_shippingmethod_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
