# Generated by Django 4.1.5 on 2023-04-03 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_shippingmethod_officevendor_default_shipping_option_and_more'),
        ('orders', '0066_delete_officevendorshippingoptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororder',
            name='shipping_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vo_shipping_option', to='accounts.shippingmethod'),
        ),
    ]
