# Generated by Django 4.1.6 on 2023-04-11 07:46

from django.db import migrations

REMOVE_MONTH_PROCEDURES = """
DELETE FROM orders_procedure WHERE
type='month'
"""
class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_shippingmethod_officevendor_default_shipping_option_and_more"),
        ("orders", "0067_vendororder_shipping_option"),
    ]

    operations = [
        migrations.RunSQL(REMOVE_MONTH_PROCEDURES),
        migrations.AlterUniqueTogether(
            name="procedure",
            unique_together={("office", "procedurecode", "start_date")},
        ),
        migrations.RemoveField(
            model_name="procedure",
            name="type",
        ),
    ]
