# Generated by Django 4.1.6 on 2023-04-17 18:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0070_search_optimizations"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="vendors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=list, help_text="Child vendors", size=None
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="child_count",
            field=models.IntegerField(default=0, help_text="Child count"),
        ),
    ]
