# Generated by Django 4.1.6 on 2023-04-17 18:30

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0072_fill_vendor_ids"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                condition=models.Q(("parent_id", None)), fields=["vendors"], name="child_vendors_gin_idx"
            ),
        ),
    ]
