# Generated by Django 4.1.6 on 2023-04-24 12:39

from django.db import migrations

CLEANUP_SQL = """
WITH parents as (
        SELECT DISTINCT parent_id FROM orders_product WHERE parent_id IS NOT NULL
    ),
    parent_office_products AS (SELECT ofp.id, ofp.product_id, ofp.last_order_date, ofp.last_order_price, op.name, ofp.office_id
                           FROM orders_officeproduct ofp
                                    INNER JOIN parents p ON ofp.product_id = p.parent_id
                                    JOIN orders_product op on ofp.product_id = op.id)
DELETE FROM orders_officeproduct
WHERE id in (SELECT id from parent_office_products)
"""

class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0073_product_child_vendors_gin_idx"),
    ]

    operations = [
        migrations.RunSQL(CLEANUP_SQL, migrations.RunSQL.noop)
    ]
