# Generated by Django 4.1.6 on 2023-04-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0074_remove_parent_office_products"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["manufacturer_number"], name="product_manufacturer_idx"),
        ),
    ]
