# Generated by Django 4.1.6 on 2023-04-30 19:28

from django.db import migrations

FILL_VENDOR_IDS_SQL = """
WITH parent_vendors AS (SELECT op2.parent_id, array_agg(DISTINCT vendor_id) as parent_vendors, count(*) as calc_child_count
                        FROM orders_product op2
                        GROUP BY op2.parent_id)
UPDATE orders_product op
SET vendors = parent_vendors, child_count = calc_child_count
FROM parent_vendors pv
WHERE pv.parent_id = op.id;
"""

class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0075_product_product_manufacturer_idx"),
    ]

    operations = [
        migrations.RunSQL(FILL_VENDOR_IDS_SQL, migrations.RunSQL.noop)
    ]
