# Generated by Django 4.1.6 on 2023-05-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0079_auto_20230509_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
