# Generated by Django 4.1.5 on 2023-05-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0080_product_vendor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('redundancy', 'Ordo Order - Redundancy'), ('ordo', 'Ordo Order'), ('vendor', 'Vendor Direct')], default='redundancy', max_length=100),
        ),
    ]
