# Generated by Django 3.2.6 on 2021-11-12 19:04

import django.db.models.deletion
from django.db import migrations

import apps.common.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officevendor',
            name='office',
            field=apps.common.models.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_vendors', to='accounts.office'),
        ),
        migrations.AlterField(
            model_name='officevendor',
            name='vendor',
            field=apps.common.models.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_offices', to='accounts.vendor'),
        ),
    ]
