# Generated by Django 3.2.6 on 2021-09-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendors'),
        ),
        migrations.AlterField(
            model_name='office',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='offices'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
