# Generated by Django 3.2.6 on 2021-08-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="office",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
