# Generated by Django 3.2.6 on 2021-09-07 11:54

from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymember',
            name='token_expires_at',
            field=models.DateTimeField(default=apps.accounts.models.default_expires_at),
        ),
    ]
