# Generated by Django 3.2.6 on 2021-11-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officeaddress',
            options={'ordering': ('address_type',)},
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
