# Generated by Django 3.2.6 on 2021-09-15 03:51

import django.db.models.deletion
import month.models
from django.db import migrations, models

import apps.common.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='budget',
        ),
        migrations.CreateModel(
            name='OfficeBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_type', models.CharField(choices=[('production', 'Adjusted Production'), ('collection', 'Collection')], default='production', max_length=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('month', month.models.MonthField(auto_now_add=True)),
                ('office', apps.common.models.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounts.office')),
            ],
            options={
                'unique_together': {('office', 'month')},
            },
        ),
    ]
