# Generated by Django 3.2.6 on 2021-10-13 10:53

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_officevendor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='office',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
