# Generated by Django 3.2.6 on 2021-10-13 20:33

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_officevendor_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='officevendor',
            name='task_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='office',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
