# Generated by Django 3.2.6 on 2021-11-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211112_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officebudget',
            old_name='budget',
            new_name='dental_budget',
        ),
        migrations.RenameField(
            model_name='officebudget',
            old_name='budget_type',
            new_name='dental_budget_type',
        ),
        migrations.RenameField(
            model_name='officebudget',
            old_name='percentage',
            new_name='dental_percentage',
        ),
        migrations.RenameField(
            model_name='officebudget',
            old_name='spend',
            new_name='dental_spend',
        ),
        migrations.RenameField(
            model_name='officebudget',
            old_name='total_budget',
            new_name='dental_total_budget',
        ),
        migrations.AddField(
            model_name='officebudget',
            name='office_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='officebudget',
            name='office_budget_type',
            field=models.CharField(choices=[('production', 'Adjusted Production'), ('collection', 'Collection')], default='production', max_length=10),
        ),
        migrations.AddField(
            model_name='officebudget',
            name='office_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='officebudget',
            name='office_spend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='officebudget',
            name='office_total_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
