# Generated by Django 3.2.6 on 2021-09-16 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210915_0351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officebudget',
            options={'ordering': ('-month',)},
        ),
    ]
