# Generated by Django 3.2.6 on 2021-12-03 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211202_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='cc_code',
        ),
        migrations.RemoveField(
            model_name='office',
            name='cc_expiry',
        ),
        migrations.RemoveField(
            model_name='office',
            name='cc_number',
        ),
        migrations.AddField(
            model_name='company',
            name='billing_together',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_id', models.CharField(max_length=128)),
                ('start_on', models.DateField()),
                ('cancelled_on', models.DateField(blank=True, null=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.office')),
            ],
            options={
                'ordering': ('-updated_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last4', models.CharField(blank=True, max_length=5)),
                ('customer_id', models.CharField(blank=True, max_length=70)),
                ('card_token', models.CharField(blank=True, max_length=100)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='accounts.office')),
            ],
            options={
                'ordering': ('-updated_at',),
                'abstract': False,
            },
        ),
    ]
