# Generated by Django 3.2.6 on 2021-10-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211013_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officevendor',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='officevendor',
            unique_together={('vendor', 'username'), ('office', 'vendor')},
        ),
    ]
