# Generated by Django 3.2.6 on 2021-08-31 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210830_0343'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='officevendor',
            unique_together={('office', 'vendor')},
        ),
    ]
