# Generated by Django 3.2.6 on 2021-09-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_officebudget_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
