# Generated by Django 3.2.6 on 2021-09-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_officevendor_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
