# Generated by Django 3.2.6 on 2021-09-21 10:03

import django.db.models.deletion
import month.models
from django.db import migrations, models

import apps.common.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_office_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='address',
        ),
        migrations.AddField(
            model_name='officebudget',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='officebudget',
            name='month',
            field=month.models.MonthField(),
        ),
        migrations.CreateModel(
            name='OfficeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_type', models.CharField(choices=[('address', 'Address'), ('billing', 'Billing Address')], default='address', max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('office', apps.common.models.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.office')),
            ],
            options={
                'ordering': ('-updated_at',),
                'abstract': False,
            },
        ),
    ]
