# Generated by Django 3.2.6 on 2022-01-04 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211203_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymember',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to=settings.AUTH_USER_MODEL),
        ),
    ]
