# Generated by Django 3.2.6 on 2021-10-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211015_0409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ('created_at',)},
        ),
    ]
