# Generated by Django 3.2.6 on 2021-09-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210921_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='postal_code',
        ),
        migrations.AlterField(
            model_name='officebudget',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
