# Generated by Django 3.2.13 on 2022-06-26 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220602_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requires_approval_notification_for_all_orders', models.BooleanField(default=False)),
                ('budget_threshold', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.office')),
            ],
            options={
                'ordering': ('-updated_at',),
                'abstract': False,
            },
        ),
    ]
