# Generated by Django 3.2.13 on 2022-06-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_officesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='officesetting',
            name='percentage_threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
