# Generated by Django 3.2.13 on 2022-12-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_officesetting_percentage_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='dental_api',
            field=models.CharField(default=' ', max_length=128),
            preserve_default=False,
        ),
    ]
