# Generated by Django 4.1.6 on 2023-02-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_office_dental_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='officebudget',
            name='adjusted_production',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='officebudget',
            name='collection',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
