# Generated by Django 4.1.5 on 2023-03-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_officebudget_adjusted_production_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officevendor',
            name='login_success',
            field=models.BooleanField(default=True),
        ),
    ]
