# Generated by Django 4.1.5 on 2023-03-28 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_officevendor_login_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='shipping_options',
        ),
    ]
