# Generated by Django 4.1.6 on 2023-04-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_shippingmethod_officevendor_default_shipping_option_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="officesetting",
            name="enable_order_approval",
            field=models.BooleanField(default=True),
        ),
    ]
