# Generated by Django 4.1.6 on 2023-04-21 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_shippingmethod_officevendor_default_shipping_option_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenDentalKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name="office",
            name="dental_api",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="accounts.opendentalkey"
            ),
        ),
    ]
