# Generated by Django 4.1.5 on 2023-04-22 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_officesetting_enable_order_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenDentalKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='office',
            name='dental_api',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.opendentalkey'),
        ),
    ]
