# Generated by Django 4.2.1 on 2023-05-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_opendentalkey_alter_office_dental_api"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
