# Generated by Django 4.1.5 on 2023-05-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_vendor_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='practice_software',
            field=models.CharField(choices=[('open_dental', 'Open Dental'), ('dentirx', 'Dentirx'), ('eaglesoft', 'EagleSoft'), ('curve', 'Curve'), ('carestack', 'Carestack'), ('macpractice', 'MacPractice'), ('other', 'Other')], default='open_dental', max_length=50),
        ),
    ]
