# Generated by Django 4.2.1 on 2023-05-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_office_practice_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='officevendor',
            name='account_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
