# Generated by Django 4.2.1 on 2023-06-05 18:57
from collections import defaultdict

from django.db import migrations

NONE = 0
PRODUCTION = 1
COLLECTION = 2

BT2BASIS = {
    "production": PRODUCTION,
    "collection": COLLECTION
}


def fill_budget(apps, schema_editor):
    OfficeBudget = apps.get_model("accounts", "OfficeBudget")
    Budget = apps.get_model("accounts", "Budget")
    BudgetCategory = apps.get_model("accounts", "BudgetCategory")
    Subaccount = apps.get_model("accounts", "Subaccount")
    office_budgets = defaultdict(defaultdict)
    for ob in OfficeBudget.objects.all():
        office_budgets[ob.office_id][ob.month] = ob
    for office_id, budgets in office_budgets.items():
        budget_categories = {
            slug: BudgetCategory.objects.create(
                office_id=office_id,
                slug=slug,
                name=name,
                is_custom=False
            )
            for slug, name, basis in (
                ("dental", "Dental Budget", PRODUCTION),
                ("office", "Office Budget", PRODUCTION),
                ("misc", "Miscellaneous spend", NONE),
            )
        }
        for month, ob in budgets.items():
            budget = Budget.objects.create(
                office_id=ob.office_id,
                month=month,
                adjusted_production=ob.adjusted_production,
                collection=ob.collection,
            )
            dental_basis = BT2BASIS[ob.dental_budget_type]
            office_basis = BT2BASIS[ob.office_budget_type]
            Subaccount.objects.create(
                budget=budget,
                basis=dental_basis,
                category=budget_categories["dental"],
                percentage=ob.dental_percentage,
                spend=ob.dental_spend
            )
            Subaccount.objects.create(
                budget=budget,
                basis=office_basis,
                category=budget_categories["office"],
                percentage=ob.office_percentage,
                spend=ob.office_spend
            )
            Subaccount.objects.create(
                budget=budget,
                basis=NONE,
                category=budget_categories["misc"],
                percentage=0,
                spend=ob.miscellaneous_spend
            )



class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_budget_budgetcategory_subaccount"),
    ]

    operations = [
        migrations.RunPython(fill_budget, migrations.RunPython.noop)
    ]
