# Generated by Django 4.2.1 on 2023-06-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_alter_companymember_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subaccount",
            name="slug",
            field=models.SlugField(
                choices=[
                    ("dental", "dental"),
                    ("office", "office"),
                    ("misc", "misc"),
                    ("vendor-henry_schein", "vendor-henry_schein"),
                    ("vendor-darby", "vendor-darby"),
                    ("vendor-patterson", "vendor-patterson"),
                    ("vendor-amazon", "vendor-amazon"),
                    ("vendor-benco", "vendor-benco"),
                    ("vendor-ultradent", "vendor-ultradent"),
                    ("vendor-implant_direct", "vendor-implant_direct"),
                    ("vendor-edge_endo", "vendor-edge_endo"),
                    ("vendor-dental_city", "vendor-dental_city"),
                    ("vendor-dcdental", "vendor-dcdental"),
                    ("vendor-crazy_dental", "vendor-crazy_dental"),
                    ("vendor-purelife", "vendor-purelife"),
                    ("vendor-skydental", "vendor-skydental"),
                    ("vendor-top_glove", "vendor-top_glove"),
                    ("vendor-bluesky_bio", "vendor-bluesky_bio"),
                    ("vendor-practicon", "vendor-practicon"),
                    ("vendor-midwest_dental", "vendor-midwest_dental"),
                    ("vendor-pearson", "vendor-pearson"),
                    ("vendor-salvin", "vendor-salvin"),
                    ("vendor-bergmand", "vendor-bergmand"),
                    ("vendor-biohorizons", "vendor-biohorizons"),
                    ("vendor-atomo", "vendor-atomo"),
                    ("vendor-orthoarch", "vendor-orthoarch"),
                    ("vendor-office_depot", "vendor-office_depot"),
                    ("vendor-safco", "vendor-safco"),
                    ("vendor-net_32", "vendor-net_32"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(fields=("office", "month"), name="budget_office_month_uniq"),
        ),
        migrations.AddConstraint(
            model_name="subaccount",
            constraint=models.UniqueConstraint(fields=("budget", "slug"), name="subaccount_budget_slug_uniq"),
        ),
    ]
