version: "3"

services:
  postgres:
    image: postgres:13
    ports:
      - ${POSTGRES_PORT}:5432
    env_file: .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./devops/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
  redis:
    image: redis:6.0
    ports:
      - ${REDIS_PORT}:6379
    env_file: .env
