# Generated by Django 4.1.6 on 2023-03-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_searchhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductParentHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("operation_id", models.UUIDField()),
                ("product", models.IntegerField()),
                ("old_parent", models.IntegerField(null=True)),
                ("new_parent", models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="ProductRelationHistory",
        ),
    ]
