# Generated by Django 4.1.6 on 2023-04-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_productparenthistory_delete_productrelationhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="RollbackInformation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("operation_id", models.UUIDField(help_text="Apply operation ID")),
                (
                    "max_parent_id_before",
                    models.IntegerField(help_text="Maximum id of existing parent before operation started"),
                ),
                ("last_inserted_parent_id", models.IntegerField(help_text="Last inserted parent id", null=True)),
            ],
        ),
    ]
