# Generated by Django 4.2.1 on 2023-06-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0006_badimageurl"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderTasks",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("task_id", models.UUIDField()),
                ("order_id", models.IntegerField()),
            ],
        ),
    ]
